name: Refresh Dataset

# This workflow refreshes the Google Play certified devices dataset on a schedule.
on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download latest dataset
        run: python scripts/refresh_dataset.py

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update supported devices dataset"
          branch: dataset-refresh
          create_branch: true
          commit_user_name: github-actions
          commit_user_email: actions@github.com
